import { writeFileSync } from "fs";
import { QUESTIONS_DATA, SUBJECTS_DATA } from "./questions";
import type { SeedQuestion, SeedSubject } from "./questions";

// Deduplicate subjects by slug (keep first occurrence)
const seenSubjects = new Set<string>();
const uniqueSubjects: SeedSubject[] = SUBJECTS_DATA.filter((s) => {
  if (seenSubjects.has(s.slug)) return false;
  seenSubjects.add(s.slug);
  return true;
});

if (uniqueSubjects.length < SUBJECTS_DATA.length) {
  console.log(
    `Subjects: ${SUBJECTS_DATA.length} → ${uniqueSubjects.length} (removed ${SUBJECTS_DATA.length - uniqueSubjects.length} duplicate slugs)`
  );
}

// Deduplicate by question text (trimmed to handle whitespace differences)
const seen = new Set<string>();
const unique: SeedQuestion[] = QUESTIONS_DATA.filter((q) => {
  const key = q.text.trim();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

console.log(
  `Total: ${QUESTIONS_DATA.length} → Unique: ${unique.length} (removed ${QUESTIONS_DATA.length - unique.length} duplicates)`
);

function serializeQuestion(q: SeedQuestion): string {
  const lines = [
    `    subjectSlug: ${JSON.stringify(q.subjectSlug)}`,
    `    text: ${JSON.stringify(q.text)}`,
    `    optionA: ${JSON.stringify(q.optionA)}`,
    `    optionB: ${JSON.stringify(q.optionB)}`,
    `    optionC: ${JSON.stringify(q.optionC)}`,
    `    correctAnswer: ${JSON.stringify(q.correctAnswer)}`,
    `    source: ${JSON.stringify(q.source)}`,
    ...(q.explanation ? [`    explanation: ${JSON.stringify(q.explanation)}`] : []),
  ];
  return `  {\n${lines.join(",\n")},\n  }`;
}

function serializeSubject(s: SeedSubject): string {
  return `  { name: ${JSON.stringify(s.name)}, slug: ${JSON.stringify(s.slug)}, color: ${JSON.stringify(s.color)} }`;
}

const output = `// Auto-generated by dedupe.ts — ${new Date().toISOString().slice(0, 10)}
// Source: questions.ts deduplicated (${QUESTIONS_DATA.length} → ${unique.length} questions)

export interface SeedQuestion {
  subjectSlug: string;
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  correctAnswer: "A" | "B" | "C";
  source: string;
  explanation?: string;
}

export interface SeedSubject {
  name: string;
  slug: string;
  color: string;
}

export const SUBJECTS_DATA: SeedSubject[] = [
${uniqueSubjects.map(serializeSubject).join(",\n")},
];

export const QUESTIONS_DATA: SeedQuestion[] = [
${unique.map(serializeQuestion).join(",\n")},
];
`;

writeFileSync("seed-data/questions-unique.ts", output, "utf-8");
console.log("Written: seed-data/questions-unique.ts");
